In [1]:
print("Antas")

Antas

In [3]:
import pandas as pd
import numpy as np
try:
    import ctgan
    print("CTGAN is installed.")
except ImportError:
    print("CTGAN is not installed.")

try:
    import imblearn
    print("imblearn is installed.")
except ImportError:
    print("imblearn is not installed.")

CTGAN is not installed.
imblearn is installed.

In [4]:
!pip install ctgan

Collecting ctgan
  Downloading ctgan-0.12.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from ctgan) (2.0.2)
Requirement already satisfied: pandas>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from ctgan) (2.2.2)
Requirement already satisfied: torch>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from ctgan) (2.10.0+cpu)
Requirement already satisfied: tqdm>=4.29 in /usr/local/lib/python3.12/dist-packages (from ctgan) (4.67.3)
Collecting rdt>=1.14.0 (from ctgan)
  Downloading rdt-1.20.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.1->ctgan) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.1->ctgan) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.1->ctgan) (2025.3)
Requirement already satisfied: scipy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from rdt>=1.14.0->ctgan) (1.16.3)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from rdt>=1.14.0->ctgan) (1.6.1)
Collecting Faker!=37.11.0,>=17 (from rdt>=1.14.0->ctgan)
  Downloading faker-40.4.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (3.24.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (2025.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.1.1->ctgan) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.14.0->ctgan) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.14.0->ctgan) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.3.0->ctgan) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.3.0->ctgan) (3.0.3)
Downloading ctgan-0.12.1-py3-none-any.whl (25 kB)
Downloading rdt-1.20.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.5/74.5 kB 3.8 MB/s eta 0:00:00
Downloading faker-40.4.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 34.5 MB/s eta 0:00:00
Installing collected packages: Faker, rdt, ctgan
Successfully installed Faker-40.4.0 ctgan-0.12.1 rdt-1.20.0

In [5]:
import pandas as pd
import numpy as np
from ctgan import CTGAN
import warnings
warnings.filterwarnings('ignore')

In [6]:
#LOAD THE DATA
df = pd.read_csv('/content/dataset.csv')
print(df.head())
print("Loading done")

    Age  Gestational Age  Number of sons   Number of daughters  \
0  25.0               26                0                    0
1  28.0               35                0                    1
2  26.0               28                0                    0
3  25.0               28                0                    1
4  24.0               39                0                    0

   Total Number of Children       Gravida Female Education Husband Education  \
0                         0  Primigravida       Graduation        Graduation
1                         1  Multigravida     Intermediate            Matric
2                         0  Primigravida       Graduation        Graduation
3                         1  Multigravida       Graduation        Graduation
4                         0  Primigravida       Graduation        Graduation

  Working Status Physical Health   ... Feeling down, depressed, or hopeless  \
0      Housewife          Healthy  ...                                    3
1  Working Lady           Healthy  ...                                    2
2      Housewife          Healthy  ...                                    1
3      Housewife          Healthy  ...                                    0
4      Housewife          Healthy  ...                                    1

  Trouble falling or staying sleep or sleeping too much  \
0                                                  1
1                                                  3
2                                                  3
3                                                  3
4                                                  0

  Feeling tired or having little energy Poor appetite or overeating  \
0                                     1                           2
1                                     0                           3
2                                     2                           0
3                                     3                           3
4                                     1                           1

  Feeling badabout yourself that you are failure or have let yourself or your family down  \
0                                                  2
1                                                  1
2                                                  3
3                                                  1
4                                                  0

  Trouble concentrating on things, such as reading the newspaper or watching television   \
0                                                  3
1                                                  2
2                                                  3
3                                                  3
4                                                  0

   Moving or speaking so slowly that other people could have Noticed.   \
0                                                2.0
1                                                0.0
2                                                0.0
3                                                3.0
4                                                0.0

   Thoughts that you would be better off dead, or of hurting yourself  \
0                                                1.0
1                                                1.0
2                                                0.0
3                                                0.0
4                                                0.0

   Scalling  Labelling
0        16  Depressed
1        13  Depressed
2        13  Depressed
3        17  Depressed
4         5       Not

[5 rows x 27 columns]
Loading done

In [7]:
# Clean hidden spaces from column names and text
df.columns = df.columns.str.strip()
cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col] = df[col].astype(str).str.strip()

In [11]:
df.isnull().sum()

Age                                                                                        2
Gestational Age                                                                            0
Number of sons                                                                             0
Number of daughters                                                                        0
Total Number of Children                                                                   0
Gravida                                                                                    0
Female Education                                                                           0
Husband Education                                                                          0
Working Status                                                                             0
Physical Health                                                                            0
Previous Miscarriage                                                                       0
Sufficient Money for Basic Needs                                                           0
Current Appereance Acceptance                                                              0
Family System                                                                              0
Male Gender Preference                                                                     0
Relationship with Mother in-law                                                            0
Little interest or pleasure in doing things                                                0
Feeling down, depressed, or hopeless                                                       0
Trouble falling or staying sleep or sleeping too much                                      0
Feeling tired or having little energy                                                      0
Poor appetite or overeating                                                                0
Feeling badabout yourself that you are failure or have let yourself or your family down    0
Trouble concentrating on things, such as reading the newspaper or watching television      0
Moving or speaking so slowly that other people could have Noticed.                         6
Thoughts that you would be better off dead, or of hurting yourself                         4
Scalling                                                                                   0
Labelling                                                                                  0
dtype: int64

In [12]:
df.dropna(inplace=True)

In [13]:
df.isnull().sum()

Age                                                                                        0
Gestational Age                                                                            0
Number of sons                                                                             0
Number of daughters                                                                        0
Total Number of Children                                                                   0
Gravida                                                                                    0
Female Education                                                                           0
Husband Education                                                                          0
Working Status                                                                             0
Physical Health                                                                            0
Previous Miscarriage                                                                       0
Sufficient Money for Basic Needs                                                           0
Current Appereance Acceptance                                                              0
Family System                                                                              0
Male Gender Preference                                                                     0
Relationship with Mother in-law                                                            0
Little interest or pleasure in doing things                                                0
Feeling down, depressed, or hopeless                                                       0
Trouble falling or staying sleep or sleeping too much                                      0
Feeling tired or having little energy                                                      0
Poor appetite or overeating                                                                0
Feeling badabout yourself that you are failure or have let yourself or your family down    0
Trouble concentrating on things, such as reading the newspaper or watching television      0
Moving or speaking so slowly that other people could have Noticed.                         0
Thoughts that you would be better off dead, or of hurting yourself                         0
Scalling                                                                                   0
Labelling                                                                                  0
dtype: int64

In [8]:
# Standardize the Target Column
df['Labelling'] = df['Labelling'].map({'Depressed': 1, 'Not': 0, 'nan': np.nan})
df = df.dropna(subset=['Labelling'])
df['Labelling'] = df['Labelling'].astype(int)

# Fix known typos
if 'Current Appereance Acceptance' in df.columns:
    df['Current Appereance Acceptance'] = df['Current Appereance Acceptance'].replace({'YY': 'Yes'})

In [9]:
#GAN IMplemwntation

# CTGAN needs to know which columns are categories (text/discrete) vs continuous numbers (like Age)
discrete_columns = [
    'Gravida', 'Female Education', 'Husband Education', 'Working Status',
    'Physical Health', 'Previous Miscarriage', 'Sufficient Money for Basic Needs',
    'Current Appereance Acceptance', 'Family System', 'Male Gender Preference',
    'Relationship with Mother in-law', 'Labelling'
]

In [14]:
# 3. TRAIN THE GAN (PHASE 2)
print("Initializing CTGAN...")
#epoch =300
ctgan_model = CTGAN(epochs=300, verbose=True)

print("Training the GAN on 14,000 real patients... (This might take a few minutes)")
ctgan_model.fit(df, discrete_columns)

Initializing CTGAN...
Training the GAN on 14,000 real patients... (This might take a few minutes)

Gen. (-01.28) | Discrim. (-00.11): 100%|██████████| 300/300 [17:00<00:00,  3.40s/it]

In [16]:
rows_needed = 16000
print(f"Training complete! Generating {rows_needed} synthetic patients...")
synthetic_data = ctgan_model.sample(rows_needed)

# 5. MERGE AND SAVE
final_30k_df = pd.concat([df, synthetic_data], ignore_index=True)

print(final_30k_df.shape)

Training complete! Generating 16000 synthetic patients...
(29996, 27)

In [18]:
# Save to CSV
output_filename = '30k_ppd_CTGAN.csv'
final_30k_df.to_csv(output_filename, index=False)

print(f"Success! Final dataset shape: {final_30k_df.shape}")
print(output_filename)

Success! Final dataset shape: (29996, 27)
30k_ppd_CTGAN.csv